include: package:flutter_lints/flutter.yaml

linter:
  rules:
    non_constant_identifier_names: false
    undefined_identifier: false
    unnecessary_overrides: false
    unnecessary_null_comparison: false
    constant_identifier_names: false
    override_on_non_overriding_member: false
    prefer_single_quotes: true
    use_build_context_synchronously: false
    prefer_typing_uninitialized_variables: false
    use_super_parameters: true
    unnecessary_cast: false
